In [4]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X, y = iris.data[:, :2], iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.631578947368421

In [5]:
import numpy as np
X = np.random.random((10,5))
y = np.array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F', ])

In [6]:
y

array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F'], dtype='<U1')

In [7]:
X


array([[0.0426708 , 0.72659279, 0.07604582, 0.00830625, 0.24946852],
       [0.62892831, 0.19676108, 0.12301793, 0.56872543, 0.39531963],
       [0.91228813, 0.1138042 , 0.59484087, 0.08025387, 0.75096052],
       [0.16426929, 0.92449256, 0.25848922, 0.50616219, 0.15920093],
       [0.26338961, 0.8158629 , 0.73896308, 0.41849252, 0.71698935],
       [0.72458017, 0.9046428 , 0.22906912, 0.74867927, 0.98954737],
       [0.48949295, 0.21935582, 0.78904912, 0.29721553, 0.28629676],
       [0.99638025, 0.41350156, 0.61013128, 0.39966603, 0.16347936],
       [0.64614496, 0.25077997, 0.06289751, 0.69334304, 0.12410827],
       [0.67582355, 0.62037092, 0.31857575, 0.35576501, 0.35533353]])

In [8]:
X[X<0.7] = 0

In [9]:
X

array([[0.        , 0.72659279, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.91228813, 0.        , 0.        , 0.        , 0.75096052],
       [0.        , 0.92449256, 0.        , 0.        , 0.        ],
       [0.        , 0.8158629 , 0.73896308, 0.        , 0.71698935],
       [0.72458017, 0.9046428 , 0.        , 0.74867927, 0.98954737],
       [0.        , 0.        , 0.78904912, 0.        , 0.        ],
       [0.99638025, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [24]:
import pandas as pd

df = pd.DataFrame({'학과':['경영정보학과','경영학과','국제통상학과']})
df

학과
0  경영정보학과
1    경영학과
2  국제통상학과

Label encoding¶

In [25]:
# 레이블 인코더 임포트
from sklearn.preprocessing import LabelEncoder

depts = ['경영정보학과','경영학과','국제통상학과']

# LabelEncoder를 객체로 생성
encoder = LabelEncoder()

# fit, transform 메소드를 통한 레이블 인코딩
encoder.fit(depts)
labels = encoder.transform(depts)

print('레이블 인코딩 클래스 : ',encoder.classes_) # 인코딩 클래스는 classes_속성값으로 확인
print('레이블 인코딩 변환값 : ',labels)

레이블 인코딩 클래스 :  ['경영정보학과' '경영학과' '국제통상학과']
레이블 인코딩 변환값 :  [0 1 2]


classes_ 속성은 0번부터 순서대로 변환된 인코딩 값을 원본 데이터를 가집니다. 따라서 inverse_transform메소드를 통해 디코딩 또한 가능합니다.

In [26]:
print('디코딩 결과: ', encoder.inverse_transform(labels))

디코딩 결과:  ['경영정보학과' '경영학과' '국제통상학과']


In [27]:
df['학과'] = encoder.fit_transform(df['학과'])
df

학과
0   0
1   1
2   2

In [28]:
df['학과'] = encoder.inverse_transform(df['학과'])
df

학과
0  경영정보학과
1    경영학과
2  국제통상학과

원-핫 인코딩(One-Hot encoding)¶

원-핫 인코딩이란 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시하는 방법입니다.

In [29]:
pd.get_dummies(df)

학과_경영정보학과  학과_경영학과  학과_국제통상학과
0          1        0          0
1          0        1          0
2          0        0          1

원-핫 인코딩은 sklearn의 OneHotEncoder 클래스로 구현 가능합니다.

단 LabelEncoder와 차이점은 모든 문자열 값이 숫자형으로 변환돼야 한다는 점과 입력 값으로 2차원 데이터가 필요하다는 점입니다.

In [30]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

depts = ['경영정보학과','경영학과','국제통상학과']

# 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(depts)
labels = encoder.transform(depts)
print(labels,'\n')

# 2차원 데이터로 변환
labels = labels.reshape(-1,1)
print(labels)
print(labels.ndim,'차원\n')


# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())

[0 1 2] 

[[0]
 [1]
 [2]]
2 차원

원-핫 인코딩 데이터
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
