In [1]:
import numpy as np

#numpy를 사용하기 위해 array 형태로 만들기
data1 = [1,2,3,4,5]
array1 = np.array(data1)
print(array1)

# array 의 크기와 형태 확인
array1.shape

[1 2 3 4 5]


(5,)

In [2]:
#numpy를 사용하기 위해 array 형태로 만들기
# 데이터 유형이 다를경우 - 정수와 실수
data2 = [1 , 2 , 3 , 4 , 5.5]
array2 = np.array(data2)
print(array2)

# array 의 크기와 형태 확인
array2.shape

[1.  2.  3.  4.  5.5]


(5,)

In [3]:
#numpy를 사용하기 위해 array 형태로 만들기
# 데이터 유형이 다를 경우 - 정수와 문자
data3 = [1 , 2 , 3 , 4 , '서진수']
array3 = np.array(data3)
print(array3)

# array 의 크기와 형태 확인
array3.shape

['1' '2' '3' '4' '서진수']


(5,)

In [4]:
#array() 함수안에 리스트 바로 사용하기
array4 = np.array( [1,2,3,4,5] )
print(array4)

[1 2 3 4 5]


In [5]:
# 데이터 타입 확인하기
print('array1:',array1.dtype)
print('array2:',array2.dtype)
print('array3:',array3.dtype)
print('array4:',array4.dtype)

array1: int32
array2: float64
array3: <U11
array4: int32


In [6]:
# 2차원의 array 생성하기
array5 = np.array( [ [1,2,3],[3,4,5],[5,6,7] ])
print(array5)

array5.shape

[[1 2 3]
 [3 4 5]
 [5 6 7]]


(3, 3)

In [7]:
# reshape( ) 함수를 사용하여 차원을 변경하기
array6 = np.arange(12).reshape(4,3)
print(array6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# reshape( ) 함수를 사용하여 차원을 변경하기
array7 = array6.reshape(2,6)
print(array7)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
# reshape( ) 함수를 사용하여 차원을 변경하기
array8 = array6.reshape(-1,1)
print(array8)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [ ]:
# 참고 : reshape( ) 함수는 원본 데이터를 복사하여 복사본의 형태를 바꾸고 
# resize( ) 함수는 원본 데이터를 변경합니다

In [10]:
# array 합치기- vstack( ) / hstack( )
array9 = np.array( [ [1,2],[3,4] ])
print(array9)

array10 = np.array( [ [5,6],[7,8] ])
print(array10)
print()

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]



In [11]:
#vstack()
print('-vstack:','\n',np.vstack( (array9 , array10)) )
print()

#hstack()
print('-hstack:','\n',np.hstack( (array9 , array10)) )

-vstack: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

-hstack: 
 [[1 2 5 6]
 [3 4 7 8]]


In [12]:
# 2개 이상의 리스트를 array 로 합치기-column_stack()
import numpy as np
name = np.array(['홍길동','일지매','전우치'])
loc = np.array(['서울','부산','대전'])
print(name)
print(loc)
print()

all_data = np.column_stack( (name,loc))
print(all_data)

['홍길동' '일지매' '전우치']
['서울' '부산' '대전']

[['홍길동' '서울']
 ['일지매' '부산']
 ['전우치' '대전']]


In [13]:
# array 데이터 조회하기
# 1차원 array 조회하기
array1 = np.array([1,2,3,4,5])
print('전체값:' , array1)
print('1번째값:' , array1[0])
print('3번째값:' , array1[2])
print('2-4번째값:',array1[1:4])

전체값: [1 2 3 4 5]
1번째값: 1
3번째값: 3
2-4번째값: [2 3 4]


In [14]:
# array 데이터 조회하기
# 2차원 array 조회하기
array2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(array2)
print('\n')
print(array2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9


In [15]:
# isnan( ) 함수 - 주어진 값의 NaN 여부를 찾는 함수
np.isnan(array1)

array([False, False, False, False, False])

In [16]:
#isinf( ) 함수 - 주어진 값의 무한대 여부를 찾는 함수
np.isinf(array1)

array([False, False, False, False, False])

In [ ]:
# Pandas 를 활용한 데이터 가용성 확보

In [17]:
# 파일 불러오기
import pandas as pd
data1 = pd.read_csv("c:\\py_temp\\프로야구선수성적_타자.csv")
data1.head()

순위  선수명   팀명     타율  경기수   타수   득점   안타  2루타  3루타  홈런  타점
0   1  김선빈  KIA  0.370  137  476   84  176   34    1   5  64
1   2  박건우   두산  0.366  131  483   91  177   40    2  20  78
2   3  박민우   NC  0.363  106  388   84  141   25    4   3  47
3   4  나성범   NC  0.347  125  498  103  173   42    2  24  99
4   5  박용택   LG  0.344  138  509   83  175   23    2  14  90

In [18]:
data2 = pd.read_excel("c:\\py_temp\\프로야구선수성적_타자.xlsx")
data2.head()

순위  선수명   팀명     타율  경기수   타수   득점   안타  2루타  3루타  홈런  타점
0   1  김선빈  KIA  0.370  137  476   84  176   34    1   5  64
1   2  박건우   두산  0.366  131  483   91  177   40    2  20  78
2   3  박민우   NC  0.363  106  388   84  141   25    4   3  47
3   4  나성범   NC  0.347  125  498  103  173   42    2  24  99
4   5  박용택   LG  0.344  138  509   83  175   23    2  14  90

In [19]:
data3 = pd.read_csv("c:\\py_temp\\프로야구선수성적_타자_ANSI.csv")
data3.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte

In [20]:
data3 = pd.read_csv("c:\\py_temp\\프로야구선수성적_타자_ANSI.csv" , encoding="cp949")
data3.head()

순위  선수명   팀명     타율  경기수   타수   득점   안타  2루타  3루타  홈런  타점
0   1  김선빈  KIA  0.370  137  476   84  176   34    1   5  64
1   2  박건우   두산  0.366  131  483   91  177   40    2  20  78
2   3  박민우   NC  0.363  106  388   84  141   25    4   3  47
3   4  나성범   NC  0.347  125  498  103  173   42    2  24  99
4   5  박용택   LG  0.344  138  509   83  175   23    2  14  90

In [21]:
data3.head(3)

순위  선수명   팀명     타율  경기수   타수  득점   안타  2루타  3루타  홈런  타점
0   1  김선빈  KIA  0.370  137  476  84  176   34    1   5  64
1   2  박건우   두산  0.366  131  483  91  177   40    2  20  78
2   3  박민우   NC  0.363  106  388  84  141   25    4   3  47

In [22]:
data3.tail(3)

순위  선수명  팀명     타율  경기수   타수  득점   안타  2루타  3루타  홈런   타점
27  28  강한울  삼성  0.303  135  412  58  125    9    3   0   24
28  29   번즈  롯데  0.303  116  423  71  128   38    0  15   57
29  30  김하성  넥센  0.302  141  526  90  159   36    3  23  114

In [23]:
data3.shape

(30, 12)

In [24]:
data3.columns

Index(['순위', '선수명', '팀명', '타율', '경기수', '타수', '득점', '안타', '2루타', '3루타', '홈런',
       '타점'],
      dtype='object')

In [25]:
type(data3)

pandas.core.frame.DataFrame

In [26]:
data3.dtypes

순위       int64
선수명     object
팀명      object
타율     float64
경기수      int64
타수       int64
득점       int64
안타       int64
2루타      int64
3루타      int64
홈런       int64
타점       int64
dtype: object

In [27]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   순위      30 non-null     int64  
 1   선수명     30 non-null     object 
 2   팀명      30 non-null     object 
 3   타율      30 non-null     float64
 4   경기수     30 non-null     int64  
 5   타수      30 non-null     int64  
 6   득점      30 non-null     int64  
 7   안타      30 non-null     int64  
 8   2루타     30 non-null     int64  
 9   3루타     30 non-null     int64  
 10  홈런      30 non-null     int64  
 11  타점      30 non-null     int64  
dtypes: float64(1), int64(9), object(2)
memory usage: 2.9+ KB


In [28]:
data3.describe()

순위         타율         경기수          타수         득점          안타  \
count  30.000000  30.000000   30.000000   30.000000   30.00000   30.000000   
mean   15.500000   0.324933  131.033333  483.866667   85.70000  157.366667   
std     8.803408   0.019373   11.062466   53.011211   17.12258   20.163954   
min     1.000000   0.302000  106.000000  388.000000   52.00000  125.000000   
25%     8.250000   0.310500  123.000000  441.250000   73.00000  137.250000   
50%    15.500000   0.320000  133.500000  479.500000   85.50000  156.500000   
75%    22.750000   0.338000  140.500000  535.000000   97.25000  175.750000   
max    30.000000   0.370000  144.000000  576.000000  118.00000  193.000000   

             2루타        3루타         홈런          타점  
count  30.000000  30.000000  30.000000   30.000000  
mean   28.800000   2.600000  18.666667   84.500000  
std     8.142693   2.698659  11.099342   25.597346  
min     9.000000   0.000000   0.000000   24.000000  
25%    24.250000   1.000000  12.250000   68.250000  
50%    28.500000   2.000000  19.000000   84.500000  
75%    35.750000   3.000000  25.500000  110.000000  
max    42.000000  10.000000  46.000000  124.000000

In [29]:
data3['선수명'].head(5)

0    김선빈
1    박건우
2    박민우
3    나성범
4    박용택
Name: 선수명, dtype: object

In [30]:
data3[ ['선수명' , '팀명'] ].head(5)

선수명   팀명
0  김선빈  KIA
1  박건우   두산
2  박민우   NC
3  나성범   NC
4  박용택   LG

In [31]:
# 특정 컬럼 값을 제외한 나머지 출력하기
data3[ data3.columns.difference(['안타' , '2루타' , '3루타']) ].head(5)

경기수   득점  선수명  순위   타수     타율  타점   팀명  홈런
0  137   84  김선빈   1  476  0.370  64  KIA   5
1  131   91  박건우   2  483  0.366  78   두산  20
2  106   84  박민우   3  388  0.363  47   NC   3
3  125  103  나성범   4  498  0.347  99   NC  24
4  138   83  박용택   5  509  0.344  90   LG  14

In [32]:
# 특정 문자를 포함하는 행 삭제하기
data4 = data3[~ data3['팀명'].str.contains('두산')]
data4

순위   선수명   팀명     타율  경기수   타수   득점   안타  2루타  3루타  홈런   타점
0    1   김선빈  KIA  0.370  137  476   84  176   34    1   5   64
2    3   박민우   NC  0.363  106  388   84  141   25    4   3   47
3    4   나성범   NC  0.347  125  498  103  173   42    2  24   99
4    5   박용택   LG  0.344  138  509   83  175   23    2  14   90
5    6   최형우  KIA  0.342  142  514   98  176   36    3  26  120
7    8  로사리오   한화  0.339  119  445  100  151   30    1  37  111
8    9   손아섭   롯데  0.335  144  576  113  193   35    4  20   80
9   10   서건창   넥센  0.332  139  539   87  179   28    3   6   76
10  11   이명기  KIA  0.332  115  464   79  154   24    4   9   63
11  12   송광민   한화  0.327  117  437   71  143   26    0  13   75
12  13   이정후   넥센  0.324  144  552  111  179   29    8   2   47
13  14   전준우   롯데  0.321  110  455   76  146   27    1  18   69
14  15   이대호   롯데  0.320  142  540   73  173   13    0  34  111
15  16  버나디나  KIA  0.320  139  557  118  178   26    8  27  111
16  17    최정   SK  0.316  130  430   89  136   18    1  46  113
17  18   안치홍  KIA  0.316  132  487   95  154   29    2  21   93
18  19    러프   삼성  0.315  134  515   90  162   38    0  31  124
19  20   윤석민   kt  0.312  142  538   90  168   30    1  20  105
20  21   모창민   NC  0.312  136  474   64  148   25    3  17   90
21  22   고종욱   넥센  0.312  123  426   70  133   24    8   8   54
22  23   구자욱   삼성  0.310  144  564  108  175   39   10  21  107
23  24   김주찬  KIA  0.309  122  440   78  136   39    2  12   70
25  26   유한준   kt  0.306  133  445   52  136   19    0  13   68
27  28   강한울   삼성  0.303  135  412   58  125    9    3   0   24
28  29    번즈   롯데  0.303  116  423   71  128   38    0  15   57
29  30   김하성   넥센  0.302  141  526   90  159   36    3  23  114

In [ ]:
data3.head(5)

In [33]:
# 행 조회하기
data3.loc[0]

순위        1
선수명     김선빈
팀명      KIA
타율     0.37
경기수     137
타수      476
득점       84
안타      176
2루타      34
3루타       1
홈런        5
타점       64
Name: 0, dtype: object

In [34]:
data3.iloc[0]

순위        1
선수명     김선빈
팀명      KIA
타율     0.37
경기수     137
타수      476
득점       84
안타      176
2루타      34
3루타       1
홈런        5
타점       64
Name: 0, dtype: object

In [ ]:
member=pd.Series(['홍길동','전우치','강감찬','스티브잡스'],
                index = ['1번','2번','3번','4번'])
member

In [ ]:
member.loc[0]

In [ ]:
member.iloc[0]

In [35]:
data3.loc[ 0 : 3 ] 

순위  선수명   팀명     타율  경기수   타수   득점   안타  2루타  3루타  홈런  타점
0   1  김선빈  KIA  0.370  137  476   84  176   34    1   5  64
1   2  박건우   두산  0.366  131  483   91  177   40    2  20  78
2   3  박민우   NC  0.363  106  388   84  141   25    4   3  47
3   4  나성범   NC  0.347  125  498  103  173   42    2  24  99

In [36]:
data3.loc[  : 3 ] 

순위  선수명   팀명     타율  경기수   타수   득점   안타  2루타  3루타  홈런  타점
0   1  김선빈  KIA  0.370  137  476   84  176   34    1   5  64
1   2  박건우   두산  0.366  131  483   91  177   40    2  20  78
2   3  박민우   NC  0.363  106  388   84  141   25    4   3  47
3   4  나성범   NC  0.347  125  498  103  173   42    2  24  99

In [37]:
data3.loc[  25 :  ] 

순위  선수명  팀명     타율  경기수   타수  득점   안타  2루타  3루타  홈런   타점
25  26  유한준  kt  0.306  133  445  52  136   19    0  13   68
26  27  민병헌  두산  0.304  123  447  73  136   21    0  14   71
27  28  강한울  삼성  0.303  135  412  58  125    9    3   0   24
28  29   번즈  롯데  0.303  116  423  71  128   38    0  15   57
29  30  김하성  넥센  0.302  141  526  90  159   36    3  23  114

In [38]:
data3.loc[  25 :  , '선수명'] 

25    유한준
26    민병헌
27    강한울
28     번즈
29    김하성
Name: 선수명, dtype: object

In [39]:
data3.loc[  25 :  , ['선수명' , '팀명'] ]

선수명  팀명
25  유한준  kt
26  민병헌  두산
27  강한울  삼성
28   번즈  롯데
29  김하성  넥센

In [ ]:
data3.loc[ data3['홈런'] >= 30 ]

In [ ]:
data3.loc[ (data3['홈런'] >= 30 ), ['순위','선수명','팀명','홈런'] ]

In [ ]:
data3.loc[ (data3['홈런'] >= 30) & (data3['타점'] >= 115), ['순위','선수명','팀명','홈런', '타점'] ]

In [ ]:
data3.loc[ (data3['홈런'] >= 30) | (data3['타점'] >= 115), ['순위','선수명','팀명','홈런', '타점'] ]

In [ ]:
data3.loc[ (data3['홈런'] >= 30 ), ['순위','선수명','팀명','홈런'] ].sort_values('홈런')

In [ ]:
data3.loc[ (data3['홈런'] >= 30 ), ['순위','선수명','팀명','홈런'] ].sort_values('홈런' , ascending=[False])

In [40]:
# NaN 형과 NULL 형 관리하기
from numpy import nan as NA
import pandas as pd

member_4 = {'번호' : [1,2,3,4,5,6,7] ,
            '이름' : ['홍길동','전우치',NA,'일지매','을지문덕',NA,'김유신'],
            '매출' : [100,200,300,NA,150,NA ,250]}
member_5 = pd.DataFrame(member_4)
member_5

번호    이름     매출
0   1   홍길동  100.0
1   2   전우치  200.0
2   3   NaN  300.0
3   4   일지매    NaN
4   5  을지문덕  150.0
5   6   NaN    NaN
6   7   김유신  250.0

In [41]:
member_5.count()

번호    7
이름    5
매출    5
dtype: int64

In [42]:
import numpy as np

print('이름컬럼 결측치:',np.count_nonzero(member_5['이름'].isnull( ) ))
print('매출컬럼 이상치:',np.count_nonzero(member_5['매출'].isna( ) ))

이름컬럼 결측치: 2
매출컬럼 이상치: 2


In [ ]:
#NaN 값을 특정 값으로 변경하기
print(member_5.fillna(0) )
print()
print(member_5['이름'].fillna('이름없음'))

In [ ]:
# NaN 값 삭제하기
print(member_5)
print()
drop_member = member_5.dropna()
print(drop_member)

In [ ]:
member_5